apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv-02
  namespace: elk
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path : /data-elk-02
    type: DirectoryOrCreate 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "worker-02" 
